config/routes.rb
Rails.application.routes.draw do
  root to: "home#top"

  devise_for :users
  get "home/about" => "home#about"
  get 'search' => 'users#search'
  resources :books do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users do
    member do
      get :following_user, :follower_user
    end
  end

  # DM用
  resources :rooms, only: [:index, :create, :show]
  resources :messages, only: [:create, :edit, :update, :destroy]

  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :book
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    @post_comment = PostComment.new(post_comment_params)
    @post_comment.book_id = @book.id
    @post_comment.user_id = current_user.id
    @post_comment.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    post_comment = @book.post_comments.find(params[:id])
    post_comment.destroy
  end

  private
  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/views/post_comments/_index.html.erb
<% book.post_comments.each do |post_comment| %>
  <% post_comment_user = post_comment.user %>
  <tr>
  	<td>
  		<%= link_to user_path(post_comment_user), class: "user_#{post_comment_user.id}" do %>
    		<%= attachment_image_tag post_comment_user, :profile_image, size: "30x30", fallback: "no_image.jpg", size: "50x50" %><br>
    		<%= post_comment_user.name %>
  		<% end %>
  	</td>
  	<td><%= post_comment.comment %></td>
  	<% if current_user == post_comment_user %>
    	<td><%= link_to 'Destroy', book_post_comment_path(post_comment.book_id, post_comment.id), class: 'btn-sm btn-danger', method: :delete, remote: true %></td>
  	<% end %>
  </tr>
<% end %>

app/views/post_comments/create.js.erb
$(".post_comments").html("<%= j(render 'post_comments/index', book: @book) %>");
$("#post_comment_comment").val("");

app/views/post_comments/destroy.js.erb
$(".post_comments").html("<%= j(render 'post_comments/index', book: @book) %>");
$("#post_comment_comment").val("");