config/routes.rb
Rails.application.routes.draw do
  root to: "home#top"

  devise_for :users
  get "home/about" => "home#about"
  get 'search' => 'users#search'
  resources :books do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users do
    member do
      get :following_user, :follower_user
    end
  end

  # DM用
  resources :rooms, only: [:index, :create, :show]
  resources :messages, only: [:create, :edit, :update, :destroy]

  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, uniqueness: true
  validates :name, length: { minimum: 2 }
  validates :name, length: { maximum: 20 }
  validates :introduction, length: { maximum: 50 }

  attachment :profile_image
  has_many :books, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy # フォロー取得
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy # フォロワー取得
  has_many :following_user, through: :follower, source: :followed # 自分がフォローしている人
  has_many :follower_user, through: :followed, source: :follower # 自分をフォローしている人

  # DM用
  has_many :messages
  has_many :entries
  has_many :rooms, through: :entries

  # ユーザーをフォローする
def follow(user_id)
  follower.create(followed_id: user_id)
end

# ユーザーのフォローを外す
def unfollow(user_id)
  follower.find_by(followed_id: user_id).destroy
end

# フォローしていればtrueを返す
def following?(user)
  following_user.include?(user)
end

    def User.search(search, user_or_post, how_search)
        if user_or_post == "1"
            if how_search == "1"
                    User.where(['name LIKE ?', "%#{search}%"])
            elsif how_search == "2"
                    User.where(['name LIKE ?', "%#{search}"])
            elsif how_search == "3"
                    User.where(['name LIKE ?', "#{search}%"])
            elsif how_search == "4"
                    User.where(['name LIKE ?', "#{search}"])
            else
                    User.all
            end
         end
    end


end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
   def new
     super
     NoticeMailer.greeting.deliver_now
   end

  # POST /resource
   def create
     super
     NoticeMailer.greeting.deliver_now
   end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update]

  def index
    @users = User.all.order(id: "ASC")
    @user = User.find(current_user.id)
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = Book.where(user_id: params[:id])
    @book = Book.new

    # DM用
    if user_signed_in?
      @currentUserEntry = Entry.where(user_id: current_user.id)
      @userEntry = Entry.where(user_id: @user.id)
      unless @user.id == current_user.id
        @currentUserEntry.each do |cu|
          @userEntry.each do |u|
            if cu.room_id == u.room_id
              @haveRoom = true
              @roomId = cu.room_id
            end
          end
        end
        unless @haveRoom
          @room = Room.new
          @entry = Entry.new
        end
      end
    end
  end

  def edit
    @user = User.find(params[:id])
    @user.profile_image_id = @current_user.id
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
     render :edit
    end
  end

  def ensure_correct_user
    @user = User.find_by(id:params[:id])
    if @user.id != current_user.id
      redirect_to("/users/#{current_user.id}")
    end
  end

  def following_user
    @user = User.find(params[:id])
  end

  def follower_user
    @user = User.find(params[:id])
  end

  def search
  @user_or_post = params[:option]
    if @user_or_post == "1"
      @users = User.search(params[:search], @user_or_post, @how_search)
    else
      @books = Book.search(params[:search], @user_or_post, @how_search)
    end
  end


  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_contact.html.erb
<% if user_signed_in? %>
  <% unless @user.id == current_user.id %>
　　 <% if @haveRoom == true %>　   <!--チャットルームの有無-->
      <%= link_to "DM", room_path(@roomId) %>
    <% else %>
      <%= form_with(model:@room, local: true) do |f| %>
        <%= fields_for @entry do |e| %>
          <%= e.hidden_field :user_id, value: @user.id %>
        <% end %>
        <%= f.submit "DM" %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/users/_list.html.erb
<!--部分テンプレート-->
<h2>New book</h2>
<%= form_with model: book, local:true do |f| %>
  <div class="form-group">
    <body>Title</body>
    <%= f.text_field :title, class:"form-control" %>
  </div>
  <div class="form-group">
    <label>Opinion</label>
    <%= f.text_area :body, class:"form-control" %>
  </div>
  <button type="submit" class="btn btn-success ">Create Book</button>
<% end %>

app/views/users/_list2.html.erb
<h2>User info</h2>
<div class="user-info pb-3">
  <%= attachment_image_tag user, :profile_image, size: "100x100", fallback: "no_image.jpg" %>
  <table class="table">
    <thead>
      <th scope="col">name</th>
      <th scope="col"><%= user.name %></th>
    </thead>
    <tbody>
      <th scope="col">introduction</th>
      <th scope="col"><%= user.introduction %></th>
    </tbody>
    <tbody>
      <th scope="col">follows</th>
      <th scope="col">
        <%= link_to following_user_user_path(user) do %>
          <%= user.following_user.count %>
        <% end %>
      </th>
    </tbody>
    <tbody>
      <th scope="col">followers</th>
      <th scope="col">
        <%= link_to follower_user_user_path(user) do %>
          <%= user.follower_user.count %>
        <% end %>
        </th>
    </tbody>
  </table>
  <%= link_to edit_user_path(user) do %>
     <button type="button" class="btn btn-outline-secondary fas fa-user-cog w-100"></button>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1 class=" pt-3">User info</h1>
  <div>
  <%= form_with model: @user, local:true do |f| %>
      <% @user.errors.full_messages.each do |message| %>
        <p class="text-danger">error  <%= message %></p>
      <% end %>
  <div class="form-group">
    <p>Name</p>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <div class="form-group">
    <p>image</p>
    <%= f.attachment_field :profile_image %>
  </div>
  <div class="form-group">
    <p>Introduction</p>
    <%= f.text_area :introduction, class:"form-control" %>
  </div>
   <button type="submit" class="btn btn-secondary">Update User</button>
   <% end %>
</div>

app/views/users/follower_user.erb
<h1>Followers Users</h1>
<% if @user.followed != nil %>
    <% @user.follower_user.each do |user| %>
    <table>
      <thead>
      <th scope="col"></th>
      <th scope="col"></th>
      <th></th>
    </thead>
   <tbody>
        <td>
         <%= attachment_image_tag user, :profile_image, size: "40x40", fallback: "no_image.jpg", size: "40x40" %>
        </td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.following_user.count %></td>
        <td>フォロワー数：<%= user.follower_user.count %></td>
        <td><%= link_to "Show", user_path(user) %></td>
    </tbody>
    <% end %>
  </table>

  <% else %>
  <p>ユーザーはいません</p>
  <% end %>

app/views/users/following_user.erb
<h1>Follow Users</h1>
<% if @user.follower != nil%>
    <table>
      <thead>
      <th scope="col">image</th>
      <th scope="col">name</th>
      <th></th>
    </thead>
    <% @user.following_user.each do |user| %>
    <tbody>
        <td>
         <%= attachment_image_tag user, :profile_image, size: "40x40", fallback: "no_image.jpg", size: "40x40" %>
        </td>
        <td><%= user.name %></td>
        <td>フォロー数：<%= user.following_user.count %></td>
        <td>フォロワー数：<%= user.follower_user.count %></td>
        <td><%= link_to "Show", user_path(user) %></td>
    </tbody>
    <% end %>
  </table>
  <% else %>
  <p>ユーザーはいません</p>
  <% end %>

app/views/users/index.html.erb
<div class="container">
<div class="row">
  <div class="mx-auto pt-2">
<%= form_tag(search_path, :method => 'get') do %>
    <%= text_field_tag :search %>
    <%= select_tag(:option, options_for_select([["user", "1"],["post","2"]]))%>
    <%= select_tag(:choice, options_for_select([["あいまい検索", "1" ],["後方一致検索", "2" ],["前方一致検索", "3" ],["完全一致検索", "4" ]])) %>
    <%= submit_tag 'Search' %>
<% end %>
</div>
</div>
<div class="row center-block pt-3">
  <div class="col-md-3">
    <div class="col-12">
        <!--User infoテンプレ-->
      <div class="user-info">
       <%= render 'users/list2', user: @user %>
      </div>
    </div>
    <div class="col-1"></div>
  <div class="col-12">
        <!--部分テンプレート-->
    <div class="new-book">
      <%= render 'users/list', book: @book %>
    </div>
  </div>
 </div>

  <div class="col-md-8 offset-md-1">
    <div class="book_index">
     <div class="users_index">


    <h2>Users</h2>
     <table class="table table-hover">
    <thead>
      <th scope="col">image</th>
      <th scope="col">name</th>
      <th></th>
    </thead>
    <% @users.each do |user| %>
    <tbody>
        <td>
         <%= attachment_image_tag user, :profile_image, size: "40x40", fallback: "no_image.jpg", size: "40x40" %>
        </td>
        <td><%= user.name %></td>
        <td><%= link_to "Show", user_path(user) %></td>
        <td>フォロー数：<%= user.following_user.count %></td>
        <td>フォロワー数：<%= user.follower.count%></td>
        
        <% if current_user.following?(user) %>
        <td>
          <%= link_to 'フォロー外す', unfollow_path(user.id, order_sort: 1), method: :POST %>
        </td>
        <% else %>
        <td>
          <%= link_to 'フォローする', follow_path(user.id, order_sort: 1), method: :POST %>
        </td>
        <% end %>
    </tbody>
    <% end %>
  </table>
  </div>
   </div>
  </div>
</div>
</div>

app/views/users/search.html.erb
<div class="container">
  <div class="row">
    <div class="mx-auto pt-2">
   <%= form_tag(search_path, :method => 'get') do %>
    <%= text_field_tag :search %>
    <%= select_tag(:option, options_for_select([["user", "1"],["book","2"]]))%>
    <%= select_tag(:choice, options_for_select([["あいまい検索", "1" ],["後方一致検索", "2" ],["前方一致検索", "3" ],["完全一致検索", "4" ]])) %>
    <%= submit_tag 'Search' %>
   <% end %>
   </div>
  </div>

<div class=" row search_index">
<% if @user_or_post == "1"%>
    <h1>Books search for "<%= params[:search] %>"</h1>
    <table class="table">
      <thead>
        <tr>
          <th scope="col"></th>
          <th scope="col">name</th>
        </tr>
        </thead>
    <% @users.each do |user| %>
     <tbody>
       <td><%= attachment_image_tag user, :profile_image, size: "40x40", fallback: "no_image.jpg", size: "40x40" %></td>
       <td><%= user.name%></td>
     </tbody>
    <% end %>
  </table>

<% elsif @user_or_post == "2" %>
    <h2>Books search for "<%= params[:search] %>"</h2>
    <table class="table">
        <thead>
          <tr>
              <th scope="col">title</th>
              <th scope="col">opinion</th>
          </tr>
        </thead>
    <% @books.each do |book| %>
     <tbody>
       <td><%= attachment_image_tag book.user, :profile_image, size: "40x40", fallback: "no_image.jpg", size: "40x40" %></td>
       <td>
         <%= link_to book_path(book) do %>
           <%= book.title %>
         <% end %>
        </td>
       <td><%= book.body %></td>
     </tbody>
    <% end %>
    </table>
<% else %>

<% end %>
   </div>
 </div>

app/views/users/show.html.erb
<div class="row center-block pt-3">
  <div class="col-md-3">
    <div class="col-12">
        <!--User infoテンプレ-->
      <div class="user-info">
       <%= render 'users/list2', user: @user %>
      </div>
      <div>
        <%= render "users/contact" %>
      </div>
    </div>
  <div>
    <% if @user.id != current_user.id %>
    <% if current_user.following?(@user) %>
        <td>
          <%= link_to 'フォロー外す', unfollow_path(@user.id, order_sort: 0), class: "btn btn-primary", method: :POST %>
        </td>
      <% else %>
        <td>
          <%= link_to 'フォローする', follow_path(@user.id, order_sort: 0), class: "btn btn-success", method: :POST %>
        </td>
      <% end %>
    <% end %>
  </div>
  <div class="col-12">
        <!--部分テンプレート-->
    <div class="new-book">
    <%= render 'users/list', book: @book %>
    </div>
  </div>
 </div>
  <div class="col-md-8 offset-md-1">
    <div class="book_index">
     <div class="users_index">
    <h2>Books</h2>
    <table class="table table-hover">
     <thead>
     <th></th>
     <th scope="col">Title</th>
     <th scope="col">Opinion</th>
     </thead>
     <% @books.each do |book| %>
     <tbody>
     <td>
        <%= link_to user_path(@user.id) do %>
          <%= attachment_image_tag book.user, :profile_image, size: "40x40", fallback: "no_image.jpg", size: "40x40" %>
        <% end %>
     </td>
     <td>
      <%= link_to book_path(book.id) do%>
        <%= book.title %>
      <% end %>
     </td>
     <td><%= book.body %></td>
  </tbody>
     <% end %>
    </table>
</div>
   </div>
  </div>
</div>