config/routes.rb
Rails.application.routes.draw do
  root to: "home#top"

  devise_for :users
  get "home/about" => "home#about"
  get 'search' => 'users#search'
  resources :books do
    resources :post_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end

  resources :users do
    member do
      get :following_user, :follower_user
    end
  end

  # DM用
  resources :rooms, only: [:index, :create, :show]
  resources :messages, only: [:create, :edit, :update, :destroy]

  post 'follow/:id' => 'relationships#follow', as: 'follow' # フォローする
  post 'unfollow/:id' => 'relationships#unfollow', as: 'unfollow' # フォロー外す
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true, length: { maximum: 200 }

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

#post.rb
def Book.search(search, user_or_post, how_search)
  if how_search == "1"
    Book.where(['title LIKE ?', "%#{search}%"])
  elsif how_search == "2"
    Book.where(['title LIKE ?', "%#{search}"])
  elsif how_search == "3"
    Book.where(['title LIKE ?', "#{search}%"])
  elsif how_search == "4"
    Book.where(['title LIKE ?', "#{search}"])
  else
     Book.all
  end
end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def index
    @books = Book.all.order(id: "ASC")
    @book = Book.new
    @user = User.find(current_user.id)
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @user = User.find(current_user.id)
      @books = Book.all.order(id: "ASC")
      render :index
    end
  end

  def show
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    @booknew = Book.new
    @usershow = User.find(current_user.id)
    @post_comment = PostComment.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
     redirect_to book_path(@book)
    else
     render ("edit")
    end
  end

  def destroy
    book = Book.find(params[:id])
    if book.destroy
    redirect_to books_path
    end
  end

  def ensure_correct_user
    @book = Book.find_by(id:params[:id])
    if @book.user_id != current_user.id
      redirect_to("/books")
    end
  end

  private
  def book_params
      params.require(:book).permit(:title, :body, :user_id)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1 class=" pt-3">Editing Book</h1>
  <%= form_with model: @book, local:true do |f| %>
    <% if @book.errors.any? %>
       <% @book.errors.full_messages.each do |message| %>
       <p>error <%= message %></p>
       <% end %>
    <% end %>
     <div class="form-group">
      <body>Title</body>
      <%= f.text_field :title, class:"form-control" %>
    </div>
     <div class="form-group">
      <label>Opinion</label>
      <%= f.text_area :body, class:"form-control" %>
    </div>
    <button type="submit" class="btn btn-success text-center">Update Book</button>
    <% end %>
  <div class="pt-3">
    <%= link_to "Show", book_path(@book.id) %> | <%= link_to "Back", books_path %>
  </div>

app/views/books/index.html.erb
<% if @book.errors.any? %>
       <% @book.errors.full_messages.each do |message| %>
       <p class="text-danger">error <%= message %></p>
       <% end %>
<% end %>

<div class="container">
  <div class="row">
    <div class="mx-auto pt-2">
   <div>
  <% if user_signed_in? %>
   <%= form_tag(search_path, :method => 'get') do %>
    <%= text_field_tag :search %>
    <%= select_tag(:option, options_for_select([["user", "1"],["book","2"]]))%>
    <%= select_tag(:choice, options_for_select([["あいまい検索", "1" ],["後方一致検索", "2" ],["前方一致検索", "3" ],["完全一致検索", "4" ]])) %>
    <%= submit_tag 'Search' %>
   <% end %>
   </div>
  </div>
 </div>

  <div class="row center-block pt-3">
  <div class="col-md-3">
    <div class="col-12">
        <!--User infoテンプレ-->
      <div class="user-info">
       <%= render 'users/list2', user: @user %>
      </div>
  </div>
    <div class="col-12">
        <!--部分テンプレート-->
    <div class="new-book">
    <%= render 'users/list', book: @book %>
    </div>
  </div>
 </div>

  <div class="col-md-8 offset-md-1">
    <div>
      <h2>Books</h2>
     <table class="table table-hover">
      <thead>
      <th></th>
       <th scope="col">title</th>
       <th scope="col">Opinion</th>
       <th></th>
      </thead>
      <% @books.each do |book| %>
      <tbody>
        <td>
          <%= link_to "/users/#{book.user_id}" do %>
            <%= attachment_image_tag book.user, :profile_image, size: "40x40", fallback: "no_image.jpg", size: "40x40" %>
          <% end %>
        </td>
        <td>
          <%= link_to "/books/#{book.id}" do %>
            <%= book.title %>
          <% end %>
        </td>
        <td><%= book.body %></td>
        <td>
            <!--いいねのajax-->
          <div id="favorites_buttons_<%= book.id %>">
            <%= render 'favorites/favorite', book: book %>
          </div>
          
        </td>
         <td>コメント数：<%= book.post_comments.count%></td>
      </tbody>
      <% end %>
    </table>
   </div>
  </div>
</div>
</div>
<% end %>

app/views/books/search.html.erb
<div class="container">
  <div class="row">
<div class="col-12 pt-3 pb-2 w-100">
  <div class="mx-auto w-60">
  <%= form_tag( book_search_path, :method => 'get', local: true) do %>
    <%= text_field_tag :search %>
    <%= submit_tag 'Search' %>
<% end %>
</div>
</div>
<div class="col-12" >
  <h1>Books search for "<%= params[:search] %>"</h1>
  <div>
    <table class="table">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">Title</th>
      <th scope="col">Opinion</th>
    </tr>
  </thead>
<% @books.each do |book| %>
  <tbody>
      <td><%= attachment_image_tag book.user, :profile_image, size: "40x40", fallback: "no_image.jpg", size: "40x40" %></td>
      <td><%= book.title %></td>
      <td><%= book.body %></td>
    </tbody>
    <% end %>
  </table>
</div>
</div>
</div>
</div>

app/views/books/show.html.erb
<div class="row center-block pt-3">
  <div class="side-bar col-md-3 mw-25">
    <div class="col-12">
        <!--User infoテンプレ-->
      <div class="user-info">
       <%= render 'users/list2', user: @user %>
      </div>
    </div>
    <div class="col-12">
        <!--部分テンプレート-->
    <div class="new-book">
    <%= render 'users/list', book: @booknew %>
    </div>
  </div>
 </div>
  <div class="col-md-8 offset-md-1">
    <div class="book_index">
      <h2>Book detail</h2>
      <table class="table table-hover">
        <!--ajax範囲-->
        <tr id="book_<%= @book.id %>">
        <td>
          <div class="d-flex">
          <div>
          <%= link_to user_path(@book.user_id) do %>
            <%= attachment_image_tag @user, :profile_image, size: "40x40", fallback: "no_image.jpg", size: "40x40" %>
          <% end %>
          </div>
          <div>
          <%= link_to user_path(@book.user_id) do %>
            <%= @user.name %>
          <% end %>
           </div>
          </div>
        </td>
        <td><%= link_to @book.title, book_path(@book.id)%></td>
        <td><%= @book.body %></td>
        <td><div id="favorites_buttons_<%= @book.id %>"><%= render 'favorites/favorite', book: @book %></div></td>
      <% if @user.id == current_user.id %>
        <td><%= link_to "Edit", "/books/#{@book.id}/edit", {class: "btn btn-success"}%></td>
        <td><%= link_to "Destroy", "/books/#{@book.id}", class: "btn btn-danger", method: :delete, data: { confirm: '本当に消しますか？' }%></td>
      <% end %>
    　　</tr>
    　　<!---->
   </table>
   </div>

   <!--コメント一覧-->
    <table class="post_comments">
      <%= render 'post_comments/index', book: @book %>
    </table>
　　<!--コメント投稿フォーム-->
    <div id="comment_form">
      <%= form_with model:[@book,@post_comment], data: {"turbolinks" => false} do |f| %>
        <%= f.text_area :comment, size:"40x5" %>
        <%= f.submit '送信'%>
      <% end %>
    </div>
  </div>
</div>